apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # Prevents dynamic provisioning
  claimRef:
    name: mysql-pvc
    namespace: default  # Ensure this matches your PVC's namespace
  hostPath:
    path: /tmp/mysql-data   # adjust this path as needed