apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.27.4
        - name: busybox-container
          image: busybox
          command: ["sh", "-c", "while true; do echo Hello from BusyBox; sleep 5; done"]